<?php

namespace App\Filament\Resources;

use App\Filament\Resources\DiligenciamientoResource\Pages;
use App\Filament\Resources\DiligenciamientoResource\RelationManagers;
use App\Models\Diligenciamiento;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class DiligenciamientoResource extends Resource
{
    protected static ?string $model = Diligenciamiento::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('usuario_movil')
                    ->required()
                    ->maxLength(191),
                Forms\Components\DateTimePicker::make('fecha_operacion')
                    ->required(),
                Forms\Components\TextInput::make('gps_latitud')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('gps_longitud')
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('gps_altitud')
                    ->numeric(),
                Forms\Components\TextInput::make('pdf')
                    ->maxLength(191),
                Forms\Components\TextInput::make('version')
                    ->maxLength(191),
                Forms\Components\TextInput::make('fuente')
                    ->maxLength(191),
                Forms\Components\Textarea::make('declaracion_legal')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('ficha_no')
                    ->maxLength(191),
                Forms\Components\TextInput::make('foto_sticker')
                    ->maxLength(191),
                Forms\Components\TextInput::make('departamento')
                    ->maxLength(191),
                Forms\Components\TextInput::make('municipio')
                    ->maxLength(191),
                Forms\Components\TextInput::make('centro_poblado')
                    ->maxLength(191),
                Forms\Components\TextInput::make('direccion')
                    ->maxLength(191),
                Forms\Components\TextInput::make('informante_calificado')
                    ->maxLength(191),
                Forms\Components\DateTimePicker::make('fecha_diligenciamiento'),
                Forms\Components\TextInput::make('primer_nombre')
                    ->maxLength(191),
                Forms\Components\TextInput::make('segundo_nombre')
                    ->maxLength(191),
                Forms\Components\TextInput::make('primer_apellido')
                    ->maxLength(191),
                Forms\Components\TextInput::make('segundo_apellido')
                    ->maxLength(191),
                Forms\Components\Textarea::make('excepciones')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('firma')
                    ->maxLength(191),
                Forms\Components\TextInput::make('no_firma_por')
                    ->maxLength(191),
                Forms\Components\TextInput::make('correo_electronico')
                    ->maxLength(191),
                Forms\Components\TextInput::make('telefono_contacto')
                    ->tel()
                    ->maxLength(191),
                Forms\Components\TextInput::make('tipo_vivienda')
                    ->maxLength(191),
                Forms\Components\TextInput::make('material_paredes')
                    ->maxLength(191),
                Forms\Components\TextInput::make('material_pisos')
                    ->maxLength(191),
                Forms\Components\Textarea::make('servicios_publicos')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('cuartos')
                    ->numeric(),
                Forms\Components\TextInput::make('grupos_presupuesto')
                    ->numeric(),
                Forms\Components\TextInput::make('hogar_numero')
                    ->numeric(),
                Forms\Components\TextInput::make('vivienda_ocupada')
                    ->maxLength(191),
                Forms\Components\TextInput::make('tipo_sanitario')
                    ->maxLength(191),
                Forms\Components\TextInput::make('agua_consumo')
                    ->maxLength(191),
                Forms\Components\Toggle::make('agua_7_dias'),
                Forms\Components\Toggle::make('agua_24_horas'),
                Forms\Components\TextInput::make('ubicacion_sanitario')
                    ->maxLength(191),
                Forms\Components\TextInput::make('sanitario_tipo')
                    ->maxLength(191),
                Forms\Components\TextInput::make('agua_beber')
                    ->maxLength(191),
                Forms\Components\TextInput::make('eliminacion_basura')
                    ->maxLength(191),
                Forms\Components\Toggle::make('tiene_cocina'),
                Forms\Components\TextInput::make('ubicacion_cocina')
                    ->maxLength(191),
                Forms\Components\TextInput::make('combustible_cocina')
                    ->maxLength(191),
                Forms\Components\TextInput::make('gasto_alimentacion')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_transporte')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_educacion')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_salud')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_servicios_publicos')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_celular')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_arriendo')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_otros')
                    ->numeric(),
                Forms\Components\TextInput::make('gasto_suma')
                    ->numeric(),
                Forms\Components\TextInput::make('tiempo_habitando')
                    ->numeric(),
                Forms\Components\TextInput::make('eventos_afectado'),
                Forms\Components\TextInput::make('total_personas')
                    ->numeric(),
                Forms\Components\TextInput::make('total_documentos_validos')
                    ->numeric(),
                Forms\Components\TextInput::make('mujeres_8_mas')
                    ->numeric(),
                Forms\Components\Toggle::make('participo_elecciones'),
                Forms\Components\TextInput::make('puesto_votacion')
                    ->maxLength(191),
                Forms\Components\TextInput::make('tipo_ab')
                    ->maxLength(191),
                Forms\Components\TextInput::make('apellidos_completos')
                    ->maxLength(191),
                Forms\Components\TextInput::make('nombres_completos')
                    ->maxLength(191),
                Forms\Components\TextInput::make('sexo')
                    ->maxLength(191),
                Forms\Components\TextInput::make('tipo_documento_nacionales')
                    ->maxLength(191),
                Forms\Components\TextInput::make('tipo_documento_extranjeros')
                    ->maxLength(191),
                Forms\Components\TextInput::make('numero_documento')
                    ->maxLength(191),
                Forms\Components\DatePicker::make('fecha_nacimiento'),
                Forms\Components\TextInput::make('edad')
                    ->numeric(),
                Forms\Components\TextInput::make('clasificacion')
                    ->maxLength(191),
                Forms\Components\TextInput::make('limitantes_permanentes'),
                Forms\Components\TextInput::make('tipo_discapacidad')
                    ->maxLength(191),
                Forms\Components\TextInput::make('regimen_salud')
                    ->maxLength(191),
                Forms\Components\Toggle::make('problema_salud_30_dias'),
                Forms\Components\Toggle::make('acudio_servicios_salud'),
                Forms\Components\Toggle::make('fue_atendido'),
                Forms\Components\Toggle::make('embarazada'),
                Forms\Components\TextInput::make('hijos_vivos')
                    ->numeric(),
                Forms\Components\Toggle::make('desayuno_almuerzo'),
                Forms\Components\Toggle::make('sabe_leer_escribir'),
                Forms\Components\Toggle::make('actualmente_estudia'),
                Forms\Components\TextInput::make('nivel_educativo')
                    ->maxLength(191),
                Forms\Components\Toggle::make('cotiza_pensiones'),
                Forms\Components\TextInput::make('actividad_principal')
                    ->maxLength(191),
                Forms\Components\TextInput::make('condicion_trabajo')
                    ->maxLength(191),
                Forms\Components\Toggle::make('recibe_subsidio'),
                Forms\Components\Toggle::make('grupo_vulnerable'),
                Forms\Components\Toggle::make('experimento_discriminacion'),
                Forms\Components\Toggle::make('victima_violencia'),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('usuario_movil')
                    ->searchable(),
                Tables\Columns\TextColumn::make('fecha_operacion')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gps_latitud')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gps_longitud')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gps_altitud')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('pdf')
                    ->searchable(),
                Tables\Columns\TextColumn::make('version')
                    ->searchable(),
                Tables\Columns\TextColumn::make('fuente')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ficha_no')
                    ->searchable(),
                Tables\Columns\TextColumn::make('foto_sticker')
                    ->searchable(),
                Tables\Columns\TextColumn::make('departamento')
                    ->searchable(),
                Tables\Columns\TextColumn::make('municipio')
                    ->searchable(),
                Tables\Columns\TextColumn::make('centro_poblado')
                    ->searchable(),
                Tables\Columns\TextColumn::make('direccion')
                    ->searchable(),
                Tables\Columns\TextColumn::make('informante_calificado')
                    ->searchable(),
                Tables\Columns\TextColumn::make('fecha_diligenciamiento')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('primer_nombre')
                    ->searchable(),
                Tables\Columns\TextColumn::make('segundo_nombre')
                    ->searchable(),
                Tables\Columns\TextColumn::make('primer_apellido')
                    ->searchable(),
                Tables\Columns\TextColumn::make('segundo_apellido')
                    ->searchable(),
                Tables\Columns\TextColumn::make('firma')
                    ->searchable(),
                Tables\Columns\TextColumn::make('no_firma_por')
                    ->searchable(),
                Tables\Columns\TextColumn::make('correo_electronico')
                    ->searchable(),
                Tables\Columns\TextColumn::make('telefono_contacto')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tipo_vivienda')
                    ->searchable(),
                Tables\Columns\TextColumn::make('material_paredes')
                    ->searchable(),
                Tables\Columns\TextColumn::make('material_pisos')
                    ->searchable(),
                Tables\Columns\TextColumn::make('cuartos')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('grupos_presupuesto')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('hogar_numero')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('vivienda_ocupada')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tipo_sanitario')
                    ->searchable(),
                Tables\Columns\TextColumn::make('agua_consumo')
                    ->searchable(),
                Tables\Columns\IconColumn::make('agua_7_dias')
                    ->boolean(),
                Tables\Columns\IconColumn::make('agua_24_horas')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ubicacion_sanitario')
                    ->searchable(),
                Tables\Columns\TextColumn::make('sanitario_tipo')
                    ->searchable(),
                Tables\Columns\TextColumn::make('agua_beber')
                    ->searchable(),
                Tables\Columns\TextColumn::make('eliminacion_basura')
                    ->searchable(),
                Tables\Columns\IconColumn::make('tiene_cocina')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ubicacion_cocina')
                    ->searchable(),
                Tables\Columns\TextColumn::make('combustible_cocina')
                    ->searchable(),
                Tables\Columns\TextColumn::make('gasto_alimentacion')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_transporte')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_educacion')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_salud')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_servicios_publicos')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_celular')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_arriendo')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_otros')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('gasto_suma')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('tiempo_habitando')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_personas')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('total_documentos_validos')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('mujeres_8_mas')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('participo_elecciones')
                    ->boolean(),
                Tables\Columns\TextColumn::make('puesto_votacion')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tipo_ab')
                    ->searchable(),
                Tables\Columns\TextColumn::make('apellidos_completos')
                    ->searchable(),
                Tables\Columns\TextColumn::make('nombres_completos')
                    ->searchable(),
                Tables\Columns\TextColumn::make('sexo')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tipo_documento_nacionales')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tipo_documento_extranjeros')
                    ->searchable(),
                Tables\Columns\TextColumn::make('numero_documento')
                    ->searchable(),
                Tables\Columns\TextColumn::make('fecha_nacimiento')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('edad')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('clasificacion')
                    ->searchable(),
                Tables\Columns\TextColumn::make('tipo_discapacidad')
                    ->searchable(),
                Tables\Columns\TextColumn::make('regimen_salud')
                    ->searchable(),
                Tables\Columns\IconColumn::make('problema_salud_30_dias')
                    ->boolean(),
                Tables\Columns\IconColumn::make('acudio_servicios_salud')
                    ->boolean(),
                Tables\Columns\IconColumn::make('fue_atendido')
                    ->boolean(),
                Tables\Columns\IconColumn::make('embarazada')
                    ->boolean(),
                Tables\Columns\TextColumn::make('hijos_vivos')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('desayuno_almuerzo')
                    ->boolean(),
                Tables\Columns\IconColumn::make('sabe_leer_escribir')
                    ->boolean(),
                Tables\Columns\IconColumn::make('actualmente_estudia')
                    ->boolean(),
                Tables\Columns\TextColumn::make('nivel_educativo')
                    ->searchable(),
                Tables\Columns\IconColumn::make('cotiza_pensiones')
                    ->boolean(),
                Tables\Columns\TextColumn::make('actividad_principal')
                    ->searchable(),
                Tables\Columns\TextColumn::make('condicion_trabajo')
                    ->searchable(),
                Tables\Columns\IconColumn::make('recibe_subsidio')
                    ->boolean(),
                Tables\Columns\IconColumn::make('grupo_vulnerable')
                    ->boolean(),
                Tables\Columns\IconColumn::make('experimento_discriminacion')
                    ->boolean(),
                Tables\Columns\IconColumn::make('victima_violencia')
                    ->boolean(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDiligenciamientos::route('/'),
            'create' => Pages\CreateDiligenciamiento::route('/create'),
            'edit' => Pages\EditDiligenciamiento::route('/{record}/edit'),
        ];
    }
}
